ALTER TABLE "Rooms"
ADD CONSTRAINT "PK_Rooms"
PRIMARY KEY ("RoomNumber");

ALTER TABLE "Rooms"
ALTER COLUMN "Price"
SET NOT NULL;

ALTER TABLE "Rooms"
ALTER COLUMN "IsAvailable"
SET NOT NULL;

ALTER TABLE "Rooms"
ALTER COLUMN "Beds"
SET NOT NULL;